### ISSUE TITLE
Issue Installing on MacOSX 10.10.5/Node 4.2.6

### ISSUE THREAD

**Issue by rdepena** [nogizhopaboroda/cmus-mediakeys#1]
From the readme it was not clear if Mac is supposed to be supported, you can look at the [debug.log here](https://gist.github.com/rdepena/4173369f46469780a9a39313a6f36007)

**Comment by rdepena** [comment]
Actually, noticed its the https://github.com/tcr/mediakey module. related https://github.com/tcr/mediakeys/issues/3

**Comment by nogizhopaboroda** [comment]
thanks for the report!

**Comment by rdepena** [comment]
@nogizhopaboroda just fyi: worked around it by switching to node 0.10 for execution. 

https://gist.github.com/rdepena/422dd295dd53a7074bb291f6a566bff4

**Comment by nogizhopaboroda** [comment]
@rdepena sent pull request to tcr/mediakeys https://github.com/tcr/mediakeys/pull/4
Using my forked version in this project for now. Rebuild passes now, just pull the fresh master.
And update Xcode to version 7.

Tried on OSX 10.11.4, node v4.0.0, Xcode 7
